"""SQLite schema and session factory for the trail tracker."""
import os
from pathlib import Path

from sqlalchemy import (
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import declarative_base, sessionmaker

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DATA_DIR.mkdir(exist_ok=True)
# Which SQLite file to use, relative to data/. Defaults to the real database;
# set RCT_DB=demo.db to run against the seeded portfolio/demo database.
DB_PATH = DATA_DIR / os.environ.get("RCT_DB", "trails.db")

engine = create_engine(f"sqlite:///{DB_PATH}", future=True)
SessionLocal = sessionmaker(bind=engine, future=True)
Base = declarative_base()


class Trail(Base):
    __tablename__ = "trails"

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False)
    geometry_geojson = Column(Text, nullable=False)
    length_meters = Column(Float, nullable=False)
    source = Column(String, nullable=False)  # "nps" or "osm"
    description = Column(Text)  # only what the source data provides
    # trail centerline split by coverage (GeoJSON MultiLineString, EPSG:4326)
    covered_foot_geojson = Column(Text)
    covered_bike_geojson = Column(Text)  # bike-only (foot takes precedence)
    uncovered_geojson = Column(Text)
    # fractions in [0, 1]
    pct_complete_foot = Column(Float, nullable=False, default=0.0)
    pct_complete_bike = Column(Float, nullable=False, default=0.0)
    pct_complete_total = Column(Float, nullable=False, default=0.0)
    is_complete = Column(Boolean, nullable=False, default=False)


class Activity(Base):
    __tablename__ = "activities"

    id = Column(Integer, primary_key=True)  # Strava activity id
    name = Column(String)
    sport_type = Column(String)
    mode = Column(String, default="foot")  # 'foot' | 'bike'
    start_date = Column(String)
    geometry_geojson = Column(Text, nullable=False)  # LineString, EPSG:4326


class SuggestedRoute(Base):
    """Routes generated by the uncovered-trail route suggester."""

    __tablename__ = "suggested_routes"

    id = Column(String, primary_key=True)  # uuid hex
    created_at = Column(String, nullable=False)
    start_lat = Column(Float, nullable=False)
    start_lng = Column(Float, nullable=False)
    target_miles = Column(Float, nullable=False)
    # FeatureCollection of route parts (connector / trail), EPSG:4326
    route_geojson = Column(Text, nullable=False)
    total_miles = Column(Float, nullable=False)
    new_coverage_miles = Column(Float, nullable=False)


class TrailActivity(Base):
    """Which activities contributed coverage to which trails."""

    __tablename__ = "trail_activities"

    trail_id = Column(Integer, ForeignKey("trails.id"), primary_key=True)
    activity_id = Column(Integer, ForeignKey("activities.id"), primary_key=True)
    overlap_meters = Column(Float, nullable=False, default=0.0)


class Meta(Base):
    """Small key/value store for scalars computed by the pipeline
    (e.g. the cached park boundary and the in-park odometer total)."""

    __tablename__ = "meta"

    key = Column(String, primary_key=True)
    value = Column(Text)


def get_meta(session, key, default=None):
    row = session.get(Meta, key)
    return row.value if row is not None else default


def set_meta(session, key, value):
    row = session.get(Meta, key)
    if row is None:
        session.add(Meta(key=key, value=value))
    else:
        row.value = value


def init_db() -> None:
    Base.metadata.create_all(engine)
